version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    collector:
        image: t-lab:collector
        build: collector
        env_file: ".env"
        depends_on:
            - "redis"

    connectors:
        image: t-lab:connectors
        build: connectors
        env_file: ".env"
        depends_on:
            - "redis"
    
    lab_api:
        image: t-lab:lab_api
        build: lab_api
        env_file: ".env"
        ports:
            - "8000:8000"
        depends_on:
            - "redis"